name: giamsat_suckhoe
description: "á»¨ng dá»¥ng giÃ¡m sÃ¡t sá»©c khá»e & nháº­n diá»‡n mÃ³n Äƒn."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # ðŸ”¥ Firebase
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  firebase_messaging: ^16.0.3

  # ðŸ“Š UI & Charts
  fl_chart: ^0.70.0
  google_fonts: ^6.2.1

  # ðŸ”” Local Storage & Notifications
  shared_preferences: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1

  # âš™ï¸ Tiá»‡n Ã­ch
  provider: ^6.1.2
  intl: ^0.18.1
  image_picker: ^1.2.0
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # ðŸ§© ThÃªm mÃ´ hÃ¬nh AI Ä‘Ã£ train
    - assets/food_model.tflite
    - assets/labels.txt